version: '3.8'
services:
  mysql:
    container_name: bridge-mysql
    image: mysql:5.7
    restart: always
    command: [--max-allowed-packet=67108864, --lower_case_table_names=1, --default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports: 
      - '3306:3306'
    networks: 
      - bridge-settlement-handler
networks:
  bridge-settlement-handler: